dist: bionic
language: go

go:
  - 1.16.x

gobuild_args: "-tags 'extlib compat pkgconfig'"

before_install:
   - sudo apt-get install libmupdf-dev

script:
 - go test -tags 'extlib compat pkgconfig' -v ./
